name: Release - Application

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Release Version
        required: true
        default: 1.0.0

run-name: 'version set to ${{ inputs.release-version }} for release'

jobs:
  modules:
    uses: codbex/codbex-infra/.github/workflows/module-release.yaml@main
    with:
      packages: codbex-number-generator-data
      release-version: ${{ inputs.release-version }}
      release-content: |
        ## codbex-number-generator-datae - ${{ inputs.release-version }}
  
        Warehouse Management - Data Sample
  
        ## Installation
  
        ```
        npm install @codbex/codbex-number-generator-data@${{ inputs.release-version }}
        ```
  
        ## Access points:
  
        - N/A
    secrets: inherit